Fix DbMaximumLengthValidator
solidusio-contrib/solidus_globalize pull request #50
Opened 2017-05-29 14:18 UTC by spaghetticode

When the length validated column is now missing (because it's translated)
the #validate method raises an exception. This patch avoids the exception.

See issue https://github.com/solidusio-contrib/solidus_globalize/issues/17.

The exception can be seen when running `rake spree_sample:load` in a
Solidus app with solidus_globalize.

2017-05-29 18:39 UTC, tvdeyen requested changes
Hey. Thanks. Please add a test

2017-05-30 14:30 UTC, spaghetticode commented
@tvdeyen I've just added a test. I am sorry it's a bit contrived, unfortunately I could not find a more straightforward and clearer way to expose the issue.

2017-06-02 05:09 UTC, tvdeyen approved these changes
Great. Thank you 😊

2017-07-17 14:18 UTC, luxflux commented
No offense, but wouldn't it be a better fit to create a patch for this on solidus instead of monkey patching? Or did you already try this?

2017-08-25 08:18 UTC, alepore commented
This was applied on #54 , thanks!

2017-08-25 08:18 UTC, closed without merging